ARG ELK_VERSION
FROM docker.elastic.co/beats/filebeat:$ELK_VERSION

#USER root
#COPY ./config/filebeat.yml /usr/share/filebeat/filebeat.yml
#RUN chown root:filebeat /usr/share/filebeat/filebeat.yml
#USER filebeat


